apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: backend
  name: ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui
  template:
    metadata:
      labels:
        app: ui
    spec:
      containers:
        - name: ui-container
          image: gauravgirase/whatclone-ui:v1.0.2
          ports:
            - containerPort: 5678
---
apiVersion: v1
kind: Service
metadata:
  name: ui
  namespace: backend
spec:
  selector:
    app: ui
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5678
