apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: backend
type: Opaque
stringData:
  SECRET_KEY:
  # Database
  DATABASE_URL: "postgresql+asyncpg://postgres:password@postgres:5432/messaging_db"
  DATABASE_URL_SYNC: "postgresql://postgres:password@postgres:5432/messaging_db"
  # Redis
  REDIS_URL: "redis://redis:6379/0"
  REDIS_PUBSUB_URL: "redis://redis:6379/1"
  REDIS_CACHE_URL: "redis://redis:6379/2"
  # S3 / File Storage
  AWS_ACCESS_KEY_ID: 
  AWS_SECRET_ACCESS_KEY:
  AWS_BUCKET_NAME: 
  AWS_REGION:
  S3_ENDPOINT_URL:
  # Celery
  CELERY_BROKER_URL: "redis://redis:6379/3"
  CELERY_RESULT_BACKEND: "redis://redis:6379/4"
